version: "2"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3333:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
  http:
      build:
        context: github.com/abiosoft/caddy-docker.git
        args:
          version: 0.10.12
      volumes:
        - type: bind
          source: ./data/sites/
          target: /var/www/sites/
        - type: bind
          source: ./data/caddypath/
          target: /var/caddy/
        - type: bind
          source: ./Caddyfile
          target: /etc/Caddyfile
      environment:
        CADDYPATH: "/var/caddy"      
      ports:
        - "443:443"
        - "80:80"
      restart: always